### ISSUE TITLE
poeditor base update

### ISSUE THREAD

**Issue by liedekef** [filesender/filesender#1235]
Hi,

several language files in the poeditor project are missing language strings (so they can't get a translation). Probably the pot-file serving as a base needs updating there? As a simple example: download_complete is not present in the NL version (but I can give several examples, even in French and English).

**Comment by WebSpider** [comment]
This probably also is the source of #1216

**Comment by monkeyiq** [comment]
It seems that some translations that have the same term id but different context are not handled properly at the moment. One example being `download_complete` as mentioned above.

**Comment by monkeyiq** [comment]
if anyone has other specific examples of terms that are missing please tag them here. I found 5 and fixed in 1291.

**Comment by liedekef** [comment]
These are still missing in lang.php in several languages (I haven't checked other languages, just parsed our logs):

No translation found for auth_sp_attribute_uid_hint in fr language
No translation found for guest_expired in en language
No translation found for guest_expired in fr language
No translation found for guest_expired in nl language
No translation found for report_event_transfer_decrypt_failed in en language
No translation found for token_has_bad_format in en language
No translation found for token_has_bad_format in fr language
No translation found for token_has_bad_format in nl language
No translation found for token_is_missing in en language
No translation found for token_is_missing in fr language
No translation found for token_is_missing in nl language
No translation found for transfer_expired in nl language
No translation found for translatable_email_not_found in en language
No translation found for translatable_email_not_found in fr language
No translation found for translatable_email_not_found in nl language
No translation found for clear_frequent_recipients in fr language
No translation found for clear_user_transfer_preferences in fr language
No translation found for collection in en language
No translation found for collection in fr language
No translation found for collection in nl language
No translation found for email_recipient_when_transfer_expires in fr language
No translation found for encryption_password_container_can_have_text_only_min_password_length_message in fr language
No translation found for file_encryption_password_must_have_numbers in fr language
No translation found for file_encryption_password_must_have_special_characters in fr language
No translation found for file_encryption_password_must_have_upper_and_lower_case in fr language
No translation found for filesender_version in en language
No translation found for most_failed_decryptions in en language
No translation found for password_can_not_be_part_of_message_error in fr language
No translation found for password_can_not_be_part_of_message_warning in fr language
No translation found for privacy_page_frequent_recipients_text in fr language
No translation found for privacy_page_trackingevents_lifetime in fr language
No translation found for report_event_transfer_decrypt_failed in fr language
No translation found for statevent_storage-expired-transfers-size in en language
No translation found for statevent_storage-free-size in en language
No translation found for statevent_upload_maxsize_ended in en language
No translation found for transfer_expired in nl language
No translation found for translatable_email_not_found in fr language

Can these be added to the poeditor so translations can be added?

**Comment by monkeyiq** [comment]
The updated list left todo them becomes (assuming with the term and English then other languages will be updated in time now that the term is exposed in poeditor):

No translation found for guest_expired in en language
No translation found for guest_expired in fr language
No translation found for guest_expired in nl language
No translation found for collection in en language
No translation found for collection in fr language
No translation found for collection in nl language
No translation found for transfer_expired in nl language

**Comment by monkeyiq** [comment]
The transfer_expired is a little strange, it exists in email and blank context in Dutch on poeditor now. Perhaps this has changed since the initial list?

**Comment by adminnr1** [comment]
Dutch translation for transfer_expired was already added 3 years ago.
Same goes for guest_expired.
If I search Poeditor for collection I can't find it (neither English or Dutch).

**Comment by monkeyiq** [comment]
I will have another look in the code to try to see where 'collection' is used.
