### ISSUE TITLE
Imporve Azure Cloud storage performance

### ISSUE THREAD

**Issue by monkeyiq** [filesender/filesender#398]
Currently 10mb chunks are writing at around 10mb/s. It would be good to get more performance if possible.
Using chunks of 20mb and it actually goes a bit lower, 7-8MB/s.

I noticed when digging into the Azure code that it uses an internal stream_for() function which uses php://temp to store the data on the way out. The php://temp has a default break point of 2mb of data to switch to using a temporary file to store the data.
http://php.net/manual/en/wrappers.php.php#wrappers.php.memory

$ php -r  'echo sys_get_temp_dir();'
/tmp

I don't imagine that this is what is really slowing things down but might be useful to see what is backing that temporary write. It might be useful to mount a tmpfs memory only backed filesenstem and set the /etc/php.ini entry to point to that location.

sys_temp_dir = "/tmp"

The interesting part is that the performance test script is largely doing the same Azure API calls. I might put some logging of time intervals in the logging code of filesender so it records at various points how long things are taking.

Is the setup using terasender, if so with how many workers? Not that the below is the recommended setting but just the keys of interest...

$config['terasender_enabled'] = true;
$config['terasender_start_mode'] = "multiple";
$config['terasender_worker_count'] = 6;

**Comment by kdermody** [comment]
**sys_temp_dir** 
I've setup a tmpfs folder and directed php to it. (confirmed that I could see the 10MB chunks appearing there)
No performance increase.

**terasender**
$config['terasender_enabled'] = true;
$config['terasender_worker_count'] = 5;
$config['terasender_start_mode'] = "multiple";

**Comment by monkeyiq** [comment]
The performance test script still gives good numbers
 
```
Connecting to Azure server took 0.01 seconds

performance testing...

       3.2 mb/s to write   1.0 mb to server, total time needed was 0.3 seconds
      12.6 mb/s to write   5.0 mb to server, total time needed was 0.4 seconds
      24.2 mb/s to write  10.0 mb to server, total time needed was 0.4 seconds
      62.3 mb/s to write  50.0 mb to server, total time needed was 0.8 seconds
      93.8 mb/s to write 100.0 mb to server, total time needed was 1.1 seconds
     123.7 mb/s to write 200.0 mb to server, total time needed was 1.6 seconds
```

**Comment by monkeyiq** [comment]
Bumping the chunk size up to 10 get’s some improvement, 10-11MB/s. Up to 20 and it actually goes a bit lower, 7-8MB/s

**Comment by monkeyiq** [comment]
I have created a thread over at [Azure Forum](https://social.msdn.microsoft.com/Forums/en-US/695f5022-6d6d-4a67-bde6-e1e88bab6134/upload-performance-from-php-can-only-get-10mbs-could-get-123mbs-on-the-pipe?forum=windowsazuredata) hoping to get some tips on what to do next for most impact.

**Comment by kdermody** [comment]
I've installed this now, but it seems to have re-introduced and earlier issue I had, preventing filesender-config.js.php from loading

(previously seen in https://github.com/filesender/filesender/pull/201#issuecomment-351959393 )

```
[Thu Aug 30 09:49:51.701080 2018] [:error] [pid 24006] [client 193.1.228.195:58707] PHP Fatal error:  Uncaught Error: Class 'SimpleSAML_Auth_Simple' not found in /opt/filesender/fs22-azure-multi/classes/auth/AuthSPSaml.class.php:216\n
Stack trace:\n
#0 /opt/filesender/fs22-azure-multi/classes/auth/AuthSPSaml.class.php(69): AuthSPSaml::loadSimpleSAML()\n
#1 /opt/filesender/fs22-azure-multi/classes/auth/AuthSP.class.php(55): AuthSPSaml::isAuthenticated()\n
#2 /opt/filesender/fs22-azure-multi/classes/auth/Auth.class.php(107): AuthSP::isAuthenticated()\n
#3 /opt/filesender/fs22-azure-multi/classes/utils/Logger.class.php(295): Auth::user()\n
#4 /opt/filesender/fs22-azure-multi/classes/utils/Logger.class.php(185): Logger::log('error', 'Looking for cla...')\n
#5 /opt/filesender/fs22-azure-multi/classes/autoload.php(116): Logger::error('Looking for cla...')\n
#6 /opt/filesender/fs22-azure-multi/classes/autoload.php(169): Autoloader::load('SimpleSAML_Auth...')\n
#7 [internal function]: {closure}('SimpleSAML_Auth...')\n
#8 /opt/filesender/fs22-azure-multi/classes/auth/AuthSPSaml.class.php(216): spl_autoload_call('SimpleSAML_Auth...')\n
#9 / in /opt/filesender/fs22-azure-multi/classes/auth/AuthSPSaml.class.php on line 216, referer: https://burly.heanet.ie/fs22-azure-multi/index.php?s=upload
```

**Comment by monkeyiq** [comment]
I just pushed an update, not ideal, but might get things going so we can get some numbers.

**Comment by kdermody** [comment]
Sorry that was a mistake on my part, I hadn't pulled in the correct branch. 

Tested with 4c92572642a499de51f5efd602ae6e35175e7cdb

Still seeing same performance average 7MB/s

but benchmark is still positive 
```
Connecting to Azure server took 0.03 seconds
performance testing...
       3.6 mb/s to write   1.0 mb to server, total time needed was 0.3 seconds
      17.1 mb/s to write   5.0 mb to server, total time needed was 0.3 seconds
      29.2 mb/s to write  10.0 mb to server, total time needed was 0.3 seconds
      47.7 mb/s to write  50.0 mb to server, total time needed was 1.0 seconds
      69.7 mb/s to write 100.0 mb to server, total time needed was 1.4 seconds
      99.1 mb/s to write 200.0 mb to server, total time needed was 2.0 seconds
```

**Comment by monkeyiq** [comment]
In the main upload path there is now a new config option that is checked and will also benchmark. If you set in your config.php file
```
$config['benchmark_writeChunk'] = 1;
```
Then in the logs you should see something like
```
[2018-09-04 11:55:09] [user 16] [rest:info] benchmark for writeChunk, data size 32437 gives 16ms
```
I will be adding something to the benchmark script shortly too. I'll comment here when that happens.

**Comment by monkeyiq** [comment]
OK I have now extended azure-simpleblob-benchmark.php to include some tests trying to do lower thresholds on forced parallel uploads. When you run the script it first does what it would have before and then tries to force 16 uploads at once for each of the chunk sizes over 5mb. For me, the parallel code kicks in by default at a 50mb chunk and I don't see much difference in the forced at 5mb numbers.

To get a better idea of when the multiple uploads are actually being used you might like to add the error_log() call to the createBlockBlobByMultipleUploadAsync() function in the downloaded file
/opt/filesender/optional-dependencies/azure/vendor/microsoft/azure-storage-blob/src/Blob/BlobRestProxy.php

```
    protected function createBlockBlobByMultipleUploadAsync(
        $container,
        $blob,
        $content,
        Models\CreateBlockBlobOptions $options = null
    ) {
        error_log('createBlockBlobByMultipleUploadAsync()');
```

**Comment by monkeyiq** [comment]
I also added some fairly ugly code to test the pageBlob API in azure-simpleblob-benchmark.php. For me, against a local azurite I get about 3mb/s but that doesn't mean anything about what performance one might get from a real azure end point.

pageBlobs were mentioned on the forum linked above, so it will be interesting to see what happens performance wise in the benchmark script.

**Comment by kdermody** [comment]
Sorry for delay, my azure account was blob only, and it didn't like pageblobs. Set up a general storage account now which is compatible. 

I'm seeing a performance increase, I've tried a few different chunk sizes and been able to burst up to 32MB/s and average 20MB/s. It some times tails off a bit, but I'm going to assume that's azure doing something on their side.

Benchmark output below

**Comment by kdermody** [comment]
```
root@burly:/tmpfs# php /opt/filesender/fs22-azure-multi/scripts/cloud/azure/azure-simpleblob-benchmark.php 
Connecting to Azure server took 0.03 seconds
performance testing using simple single API call...
       7.2 mb/s to write   1.0 mb to server, total time needed was 0.1 seconds
      34.5 mb/s to write   5.0 mb to server, total time needed was 0.1 seconds
      62.5 mb/s to write  10.0 mb to server, total time needed was 0.2 seconds
createBlockBlobByMultipleUploadAsync()
      53.6 mb/s to write  50.0 mb to server, total time needed was 0.9 seconds
createBlockBlobByMultipleUploadAsync()
      76.6 mb/s to write 100.0 mb to server, total time needed was 1.3 seconds
createBlockBlobByMultipleUploadAsync()
     124.8 mb/s to write 200.0 mb to server, total time needed was 1.6 seconds


performance testing using attempts at 16 parallel uploads...
      37.0 mb/s to write   1.0 mb to server, total time needed was 0.0 seconds
createBlockBlobByMultipleUploadAsync()
      29.2 mb/s to write   5.0 mb to server, total time needed was 0.2 seconds
createBlockBlobByMultipleUploadAsync()
      61.9 mb/s to write  10.0 mb to server, total time needed was 0.2 seconds
createBlockBlobByMultipleUploadAsync()
      70.2 mb/s to write  50.0 mb to server, total time needed was 0.7 seconds
createBlockBlobByMultipleUploadAsync()
      84.6 mb/s to write 100.0 mb to server, total time needed was 1.2 seconds
createBlockBlobByMultipleUploadAsync()
     118.6 mb/s to write 200.0 mb to server, total time needed was 1.7 seconds


performance testing using pageblob API...
 mb 1 
creating page blob for sz 1048576
start 0 end 1048575 len 1048576
      16.5 mb/s to write   1.0 mb to server, total time needed was 0.1 seconds
 mb 5 
creating page blob for sz 5242880
start 0 end 4194303 len 4194304
start 4194304 end 5242879 len 1048576
      37.6 mb/s to write   5.0 mb to server, total time needed was 0.1 seconds
 mb 10 
creating page blob for sz 10485760
start 0 end 4194303 len 4194304
start 4194304 end 8388607 len 4194304
start 8388608 end 10485759 len 2097152
      43.5 mb/s to write  10.0 mb to server, total time needed was 0.2 seconds
 mb 50 
creating page blob for sz 52428800
start 0 end 4194303 len 4194304
start 4194304 end 8388607 len 4194304
start 8388608 end 12582911 len 4194304
start 12582912 end 16777215 len 4194304
start 16777216 end 20971519 len 4194304
start 20971520 end 25165823 len 4194304
start 25165824 end 29360127 len 4194304
start 29360128 end 33554431 len 4194304
start 33554432 end 37748735 len 4194304
start 37748736 end 41943039 len 4194304
start 41943040 end 46137343 len 4194304
start 46137344 end 50331647 len 4194304
start 50331648 end 52428799 len 2097152
      41.3 mb/s to write  50.0 mb to server, total time needed was 1.2 seconds
 mb 100 
creating page blob for sz 104857600
start 0 end 4194303 len 4194304
start 4194304 end 8388607 len 4194304
start 8388608 end 12582911 len 4194304
start 12582912 end 16777215 len 4194304
start 16777216 end 20971519 len 4194304
start 20971520 end 25165823 len 4194304
start 25165824 end 29360127 len 4194304
start 29360128 end 33554431 len 4194304
start 33554432 end 37748735 len 4194304
start 37748736 end 41943039 len 4194304
start 41943040 end 46137343 len 4194304
start 46137344 end 50331647 len 4194304
start 50331648 end 54525951 len 4194304
start 54525952 end 58720255 len 4194304
start 58720256 end 62914559 len 4194304
start 62914560 end 67108863 len 4194304
start 67108864 end 71303167 len 4194304
start 71303168 end 75497471 len 4194304
start 75497472 end 79691775 len 4194304
start 79691776 end 83886079 len 4194304
start 83886080 end 88080383 len 4194304
start 88080384 end 92274687 len 4194304
start 92274688 end 96468991 len 4194304
start 96468992 end 100663295 len 4194304
start 100663296 end 104857599 len 4194304
      41.5 mb/s to write 100.0 mb to server, total time needed was 2.4 seconds
 mb 200 
creating page blob for sz 209715200
start 0 end 4194303 len 4194304
start 4194304 end 8388607 len 4194304
start 8388608 end 12582911 len 4194304
start 12582912 end 16777215 len 4194304
start 16777216 end 20971519 len 4194304
start 20971520 end 25165823 len 4194304
start 25165824 end 29360127 len 4194304
start 29360128 end 33554431 len 4194304
start 33554432 end 37748735 len 4194304
start 37748736 end 41943039 len 4194304
start 41943040 end 46137343 len 4194304
start 46137344 end 50331647 len 4194304
start 50331648 end 54525951 len 4194304
start 54525952 end 58720255 len 4194304
start 58720256 end 62914559 len 4194304
start 62914560 end 67108863 len 4194304
start 67108864 end 71303167 len 4194304
start 71303168 end 75497471 len 4194304
start 75497472 end 79691775 len 4194304
start 79691776 end 83886079 len 4194304
start 83886080 end 88080383 len 4194304
start 88080384 end 92274687 len 4194304
start 92274688 end 96468991 len 4194304
start 96468992 end 100663295 len 4194304
start 100663296 end 104857599 len 4194304
start 104857600 end 109051903 len 4194304
start 109051904 end 113246207 len 4194304
start 113246208 end 117440511 len 4194304
start 117440512 end 121634815 len 4194304
start 121634816 end 125829119 len 4194304
start 125829120 end 130023423 len 4194304
start 130023424 end 134217727 len 4194304
start 134217728 end 138412031 len 4194304
start 138412032 end 142606335 len 4194304
start 142606336 end 146800639 len 4194304
start 146800640 end 150994943 len 4194304
start 150994944 end 155189247 len 4194304
start 155189248 end 159383551 len 4194304
start 159383552 end 163577855 len 4194304
start 163577856 end 167772159 len 4194304
start 167772160 end 171966463 len 4194304
start 171966464 end 176160767 len 4194304
start 176160768 end 180355071 len 4194304
start 180355072 end 184549375 len 4194304
start 184549376 end 188743679 len 4194304
start 188743680 end 192937983 len 4194304
start 192937984 end 197132287 len 4194304
start 197132288 end 201326591 len 4194304
start 201326592 end 205520895 len 4194304
start 205520896 end 209715199 len 4194304
      41.2 mb/s to write 200.0 mb to server, total time needed was 4.9 seconds
```

**Comment by monkeyiq** [comment]
It is interesting that the page blob stuff varies less, which might be a really good thing. If a 5mb chunk can give a known speed of about 35-40mb/s if the code is converted over to page blobs it might be better than the 32mb/s burst down to 20mb using the current code. 

Using TeraSender with 4-5 workers giving 35mb/s a pop might saturate the link from the browser to you (no idea what top speed one might hope for on that link).

The code with the config
```
$config['benchmark_writeChunk'] = 1;
```
should give the same benchmark as the "performance testing using attempts at 16 parallel uploads".

In the next day or two I might port over the pageblob as an optional code path for uploading in filesender so we can see if it sustains the 35mb over 4-5 workers.

**Comment by monkeyiq** [comment]
I have just pushed some code to optionally use page blobs for file uploading. It is incomplete so has some restrictions but should hopefully be good enough to test performance and see if we want to go that way. It should give very similar performance to the page blob benchmark, ie, hopefully in the range 30-40mb/s sustained.

It only works at the moment on 4mb chunk sizes and only for files that are 4mb in size aligned (more on that later). The config.php to enable it:
```
$config['storage_type'] = 'CloudAzure';
$config['upload_chunk_size']         = 4 * 1024 * 1024;
$config['download_chunk_size']       = 4 * 1024 * 1024;
$config['upload_crypted_chunk_size'] = 4 * 1024 * 1024;

$config['benchmark_writeChunk'] = 1;
$config['azure_storage_api'] = 'pageblobs';
```

If you are using bash then an 8mb file can be made with the following. Changing the final 8 to any size of mb file that is a multiple of 4 and less than 100. The later is a temporary restriction that page blob files are all 101mb in azure land at the moment. If performance is good and we want to go page blobs then I will have some edge cases like that to clean up.

```
dd if=/dev/zero of=/tmp/pagefile bs=1024 count=$((8*1024))
```
